### ISSUE TITLE
Critical Rust issue (starting today)

### ISSUE THREAD

**Issue by Dids** [GameServerManagers/LinuxGSM#1171]
Once todays update hits, it will most definitely break everything, as there's an issue with shared library paths, and the only way around that is to manually set the library path, specifically for `libsteam_api64.so` and Steam-related stuff.

Here's a simple sample on how to fix it for a standard installation of Rust:
```
#!/bin/bash

# Do not remove this line
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/RustDedicated_Data/Plugins/x86_64

# Start the server (note that the -logfile argument is used to log to console)
./RustDedicated -batchmode +server.identity "my_server_identity" +server.hostname "My Server Name" +server.description "My Server Description" -logfile 2>&1
```

For LGSM, I noticed that if you append the path to the `executable=` line, it'll work fine.
Here's a quick sed for that (adjust to match your path):
```
sed -i -e 's#executable="./RustDedicated"#executable="LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/rustserver/serverfiles/RustDedicated_Data/Plugins/x86_64 ./RustDedicated"#g' rustserver
```

**Comment by Dids** [comment]
While this does fix the path issue, some users are also seeing segfaults. Not sure if LGSM related or not.

**Comment by testler2** [comment]
Hello, How can i fix my problem?
command_debug.sh: line 105: 26808 Segmentation fault      ${executable} ${parms}

**Comment by UltimateByte** [comment]
Facepunch...

**Comment by cedarlug** [comment]
@testler2  - Adding the LD_LIBRARY_PATH to the executable in the `rustserver` script seems to be the fix for my deployment.  No segfaults yet.

Specficially: 
```bash
rustserver@gamerig:~$ grep LD_LIBRARY rustserver
executable="LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/RustDedicated_Data/Plugins/x86_64 ./RustDedicated"
rustserver@gamerig:~$
```

**Comment by UltimateByte** [comment]
Relevant links

http://oxidemod.org/threads/problem-with-the-latest-rust-update-on-linux.21769/
http://steamcommunity.com/groups/linuxgsm/discussions/0/282992646966882793/

**Comment by Dids** [comment]
From what I've witnessed, the segfaults seem to be affecting OVH servers, more accurately those using OVH's custom kernel.

**Comment by Dids** [comment]
Note that `steamclient.so` was also moved from `RustDedicated_Data/Plugins/x86_64` to the root directory, which I've heard breaks LGSM so it halts instead of showing any errors. Copying/moving that back to the plugins directory should fix that.

**Comment by MelvynSaytek** [comment]
Hello, I moved steamclient.so to RustDedicated_Data/Plugins/x86_64 but error persist

**Comment by Dids** [comment]
You will also need the `LD_LIBRARY_PATH` fix from above.

**Comment by MelvynSaytek** [comment]
I execute grep LD_LIBRARY_PATH rustserver and grep LD_LIBRARY rustserver.
And I moved steamclient.so.
But the problem persist

**Comment by Dids** [comment]
@MelvynSaytek grep doesn't actually edit anything, it's used for searching.

The `rustserver` script has a line similar to this:
`executable="./RustDedicated"`

This needs to be changed to include the path to the Rust plugins, like this:
`executable="LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/RustDedicated_Data/Plugins/x86_64 ./RustDedicated"`

So, edit the file and make sure it's exactly as above, and it should work.

**Comment by MelvynSaytek** [comment]
it's work thank you very much !!

**Comment by UltimateByte** [comment]
So, just reproduced the issue.
Will try the fix to eventually commit this to master. I'm surprised nobody pull requested a fix already. Maybe you guys like the lack of competition with other servers.

**Comment by UltimateByte** [comment]
Fixed with the executable commands.
Working on a fresh install.

**Comment by dashdanw** [comment]
this may not work on newer systems since you're not allowed to edit LD_LIBRARY_PATH, you may need to export it at the top of the script as mentioned above or included in your rustserver users bashrc

**Comment by UltimateByte** [comment]
@dashdanw What are you calling "newer systems" ?
Because i just tested that on Debian 8. At least it will fix some (most ?) of the issues.

**Comment by cedarlug** [comment]
@UltimateByte "newer systems" == Windows 10 - it won't work there.

Seriously though, @dashdanw what are you referring to?  Your statement makes no sense.

**Comment by Dids** [comment]
@cedarlug @UltimateByte Maybe he's referring to security features of some OS's, but even then, wouldn't LD_LIBRARY_PATH simply be "local" (user bound)?

At any rate, this is fixed, awesome and thank you.

**Comment by UltimateByte** [comment]
Thanks a lot to you @Dids for pointing out the fix. You rock man !
