### ISSUE TITLE
I cannot download gmodserver

### ISSUE THREAD

**Issue by TrEnes55** [GameServerManagers/LinuxGSM#1749]
If I wanna download the gmodserver. I get the message: 

root@CT678:~# su gmodserver2
gmodserver2@CT678:/root$ cd
gmodserver2@CT678:~$ wget -N --no-check-certificate https://gameservermanagers.com/dl/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh gmodserver
converted 'https://gameservermanagers.com/dl/linuxgsm.sh' (ANSI_X3.4-1968) -> 'https://gameservermanagers.com/dl/linuxgsm.sh' (UTF-8)
--2017-12-24 13:24:54--  https://gameservermanagers.com/dl/linuxgsm.sh
Resolving gameservermanagers.com (gameservermanagers.com)... 104.31.92.238, 104.31.93.238
Connecting to gameservermanagers.com (gameservermanagers.com)|104.31.92.238|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-12-24 13:24:54 ERROR 404: Not Found.

Or

gmod@CT678:~$ wget -N --no-check-certificate https://gameservermanagers.com/dl/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh gmodserver
converted 'https://gameservermanagers.com/dl/linuxgsm.sh' (ANSI_X3.4-1968) -> 'https://gameservermanagers.com/dl/linuxgsm.sh' (UTF-8)
--2017-12-24 13:28:03--  https://gameservermanagers.com/dl/linuxgsm.sh
Resolving gameservermanagers.com (gameservermanagers.com)... 104.31.92.238, 104.31.93.238
Connecting to gameservermanagers.com (gameservermanagers.com)|104.31.92.238|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'linuxgsm.sh'

linuxgsm.sh             [ <=>                  ]  20.51K  --.-KB/s   in 0.001s

2017-12-24 13:28:03 (23.2 MB/s) - 'linuxgsm.sh' saved [21007]

linuxgsm.sh: line 1: syntax error near unexpected token `newline'
linuxgsm.sh: line 1: `<!DOCTYPE html>'

I dont know that to do.

**Comment by jalako** [comment]
same thing happeened to me just now.

**Comment by TrEnes55** [comment]
Did you found a Solution ?

**Comment by jalako** [comment]
Nope i think they just failed because you are definitely not supposed to get an html file in that format (just look at the content of the downloaded linuxgsm.sh)

**Comment by TrEnes55** [comment]
Yeahh I See Maybe the have Problems because of Christmas. I Hope they fixx it

**Comment by jalako** [comment]
seems to be fixxed now!

**Comment by NotYourMajesty** [comment]
Hmm, i still have this issue :

:~$ wget -N --no-check-certificate https://gameservermanagers.com/dl/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh gmodserver
--2017-12-24 21:21:25--  https://gameservermanagers.com/dl/linuxgsm.sh
Résolution de gameservermanagers.com (gameservermanagers.com)… 104.31.93.238, 104.31.92.238
Connexion à gameservermanagers.com (gameservermanagers.com)|104.31.93.238|:443… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2017-12-24 21:21:25 erreur 404 : Not Found.

Not yet fixed i guess :/

**Comment by TrEnes55** [comment]
Yeahh it isnt fixed der :/

**Comment by TrEnes55** [comment]
Yet*

**Comment by UltimateByte** [comment]
Temporary issue is fixed.
Up issue if not.

**Comment by NotYourMajesty** [comment]
We still have the "Not Found" issue :

wget -N --no-check-certificate https://gameservermanagers.com/dl/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh gmodserver
--2017-12-25 16:39:52--  https://gameservermanagers.com/dl/linuxgsm.sh
Résolution de gameservermanagers.com (gameservermanagers.com)… 104.31.93.238, 104.31.92.238
Connexion à gameservermanagers.com (gameservermanagers.com)|104.31.93.238|:443… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2017-12-25 16:39:52 erreur 404 : Not Found.

Tested on Gmod & Rust

**Comment by UltimateByte** [comment]
Well, i'm affraid i cannot reproduce the issue.

````
ultimatebyte@gaben:~$ wget -N --no-check-certificate https://gameservermanagers.com/dl/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh gmodserver
--2017-12-25 18:57:09--  https://gameservermanagers.com/dl/linuxgsm.sh
Resolving gameservermanagers.com (gameservermanagers.com)... 104.31.93.238, 104.31.92.238
Connecting to gameservermanagers.com (gameservermanagers.com)|104.31.93.238|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/linuxgsm.sh [following]
--2017-12-25 18:57:10--  https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/linuxgsm.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11502 (11K) [text/plain]
Saving to: ‘linuxgsm.sh’

linuxgsm.sh                                   100%[=================================================================================================>]  11.23K  --.-KB/s    in 0.007s

Last-modified header missing -- time-stamps turned off.
2017-12-25 18:57:10 (1.54 MB/s) - ‘linuxgsm.sh’ saved [11502/11502]

    fetching serverlist.csv...OK
Installed Garrys Mod server as gmodserver

./gmodserver install
````

**Comment by NotYourMajesty** [comment]
This is my distro :

```
root@ns352992:~# cat /etc/*release*
DISTRIB_ID=Debian
DISTRIB_RELEASE=8
DISTRIB_CODENAME=
DISTRIB_DESCRIPTION=
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

wget -V :

```
root@ns352992:~# wget -V
GNU Wget 1.16 compilé sur linux-gnu.

+digest +https +ipv6 +iri +large-file +nls +ntlm +opie +psl +ssl/gnutls

Wgetrc :
    /etc/wgetrc (système)
Paramètres régionaux :
    /usr/share/locale
Compilation :
    gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc"
    -DLOCALEDIR="/usr/share/locale" -I. -I../lib -I../lib
    -D_FORTIFY_SOURCE=2 -I/usr/include -g -O2 -fstack-protector-strong
    -Wformat -Werror=format-security -DNO_SSLv2 -D_FILE_OFFSET_BITS=64
    -g -Wall
Lien :
    gcc -g -O2 -fstack-protector-strong -Wformat
    -Werror=format-security -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall
    -Wl,-z,relro -L/usr/lib -lnettle -lgnutls -lz -lpsl -lidn -luuid
    -lpcre ftp-opie.o gnutls.o http-ntlm.o ../lib/libgnu.a

Copyright (C) 2014 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure
<http://www.gnu.org/licenses/gpl.html>.
Logiciel libre : vous êtes libre de le modifier ou de le redistribuer.
Il n'y a AUCUNE GARANTIE, dans les limites permises par la loi.

Écrit initialement par Hrvoje Niksic <hniksic@xemacs.org>.
Veuillez signaler toutes anomalies ou demandes à <bug-wget@gnu.org>.
```

**Comment by NotYourMajesty** [comment]
I tryied on Ubuntu 16.04 too, i still have this issue.
Same problem with my mate on Debian 9

With only `wget https://gameservermanagers.com/dl/linuxgsm.sh` it says:

`linuxgsm.sh: line 1: syntax error near unexpected token newline' linuxgsm.sh: line 1:'`

The problem appeared yesterday in the evening. Before, everything worked fine.

**Comment by NotYourMajesty** [comment]
Solved

i use `wget https://gameservermanagers.com/dl/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh gmodserver` without `-N --no-check-certificate `

**Comment by UltimateByte** [comment]
Thanks for the feedback. The --no-check-certificate is close from being removed from the doc anyways.
