### ISSUE TITLE
ANSI option appears to have no effect

### ISSUE THREAD

**Issue by jrmain** [GameServerManagers/LinuxGSM#2006]
**Describe the bug**
I recently installed a couple of servers from scratch (UT99 and UT2K4) and configured the ANSI option to be OFF (ansi="off") in the instance configs. However, I'm still seeing ANSI coloured text and ANSI codes in email alerts.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add `ansi="off"` to a server instance configuration file.
2. Run the `details` command (eg. `./ut2k4server details`).
3. ANSI coloured text is shown.

**Expected behaviour**
No ANSI coloured text.

**Minimum Information**
Game servers: UT99 and UT2K4
I'm unable to use postdetails for some reason. Details pasted below.

```
[ INFO ] Details ut2k4server: Check IP: 192.168.0.196
numfmt: invalid number: 'K'

Distro Details
==============================================================================================================================

Distro:    Ubuntu 14.04.5 LTS
Arch:      x86_64
Kernel:    3.13.0-157-generic
Hostname:  foghorn
tmux:      tmux 2.0
GLIBC:     2.19

Performance
Uptime:    16d, 1h, 22m
Avg Load:  0.43, 0.50, 0.57

Mem:       total  used   free      cached  available
Physical:  7.5GB   2.2GB  3.6GB
Swap:      7.7GB   349MB  7.4GB

Storage
==============================================================================================================================

Filesystem:      /dev/sda1
Total:           451G
Used:            118G
Available:       311G
LinuxGSM Total:  16G
Serverfiles:     5.7G

Unreal Tournament 2004 Server Details
==============================================================================================================================

Server name:      JDRGaming UT2004 Coop
Server IP:        192.168.0.196:7784
Server password:  (redacted)
Admin password:   (redacted)
Default Map:      AS-CONVOY
Status:           ONLINE

ut2k4server Script Details
==============================================================================================================================

Service name:           ut2k4server
ut2k4server version:    180908
User:                   ut2k4server
GLIBC required:         2.4
Discord alert:          on
Email alert:            off
Pushbullet alert:       off
IFTTT alert:            off
Mailgun (email) alert:  off
Pushover alert:         off
Telegram alert:         off
Location:               /home/ut2k4server
Config file:            /home/ut2k4server/serverfiles/System/ut2k4server.ini

Backups
==============================================================================================================================

No Backups created

Command-line Parameters
==============================================================================================================================

./ucc-bin server AS-CONVOY?game=UT2k4Assault.ASGameInfo -nohomedir ini=ut2k4server.ini log=/home/ut2k4server/log/server/ut2k4server-game.log

Ports
==============================================================================================================================

Change ports by editing the parameters in:
/home/ut2k4server/serverfiles/System/ut2k4server.ini

Useful port diagnostic command:
netstat -atunp | grep ucc-bin

DESCRIPTION      DIRECTION  PORT         PROTOCOL  INI VARIABLE
> Game           INBOUND    7784         udp       Port=7784
> Query          INBOUND    7785         udp
> GameSpy query  INBOUND    7794         udp       OldQueryPortNumber=7794
< Master server  OUTBOUND   28900/28902  tcp/udp
> WebAdmin       INBOUND    8075         tcp       ListenPort=8075

JDRGaming UT2004 Coop WebAdmin
==============================================================================================================================

WebAdmin enabled:   True
WebAdmin url:       http://192.168.0.196:8075
WebAdmin username:  (redacted)
WebAdmin password:  (redacted)

Status: ONLINE
```

**Comment by dgibbs64** [comment]
Issue is that core_messages load before the lgsm configs. It's a chicken and egg situation. So I will need to reload core_messages after the configs have loaded.

**Comment by dgibbs64** [comment]
Fixed for next release d9e1af2c25ad765ff013e11690c1b100b7502f74

**Comment by jrmain** [comment]
Confirmed fixed with version 181027.

**Comment by jrmain** [comment]
The `update-lgsm` command still shows some ANSI text right at the beginning. It's not visible normally, but I run `update-lgsm` in a cron job, and the cron email generated shows this (leading Esc character not shown):
``` 
[K[ .... ] Update LinuxGSM ut2k4server: Updating LinuxGSM
```
