### ISSUE TITLE
Wrong crontab syntax in Wiki

### ISSUE THREAD

**Issue by borzaka** [GameServerManagers/LinuxGSM#2033]
I copied the starting point from here: [On-Boot](https://github.com/GameServerManagers/LinuxGSM/wiki/On-Boot) Page

Edited for my server;

Not working:
`@reboot '/home/csgoserver/csgoserver start' > /dev/null 2>&1`
Working:
`@reboot /home/csgoserver/csgoserver start > /dev/null 2>&1`

Maybe the use of `'` for user based cronjobs is wrong.
In the [Cronjobs](https://github.com/GameServerManagers/LinuxGSM/wiki/Cronjobs) Wiki Page it looks like this is true: user based cronjobs has no `'`'s, only in root based.

My server:
```
csgoserver@dellserver:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch
```

**Comment by UltimateByte** [comment]
You are right, I have corrected this.
However, rebooting using monitor is advised in most cases.

Thank you for noticing and reporting this.

**Comment by borzaka** [comment]
It's still not fixed @UltimateByte

[Running on Boot](https://docs.linuxgsm.com/configuration/running-on-boot#crontab)

This is not working:
`@reboot '/home/username/gameserver monitor' > /dev/null 2>&1`

This one does:
`@reboot /home/username/gameserver monitor > /dev/null 2>&1`

The use of `'` for user based cronjobs is wrong.

Docs changes not implemented to the new one?
