### ISSUE TITLE
~/rustserver wipe not wiping hapis island saves

### ISSUE THREAD

**Issue by StaticReality** [GameServerManagers/LinuxGSM#2711]
Issues raised here are **ONLY** for:
* LinuxGSM bugs.
* Feature suggestions.
* Code contributions.

Issues raised here are **NOT** for:
* General support.
* Specific game server issues (e.g CS:GO, TF2).
* Dedicated server issues (e.g Ubuntu, CentOS).
* Anything not directly related to LinuxGSM development.

For general support visit the **[LinuxGSM-Support](https://linuxgsm.com/support)**.

***Please use the template below, deleting the above text***

## User Story

When using the 
~/rustserver wipe
command its expected to erase hapisisland save files but its not: examaple of said file:
$ ls -la ~/serverfiles/server/rustserver/ | grep hapis
-rw-rw-r-- 1 rustserver rustserver  1985028 Mar  9 17:49 hapisisland.4096.1007661659.190.sav
-rw-rw-r-- 1 rustserver rustserver  1964637 Mar  9 18:14 hapisisland.4096.1881603683.190.sav

## Basic info

* **Distro:** [Centos7]
* **Game:** [Rust]
* **Command:** [wipe]
* **LinuxGSM version:** [v19.12.5]

## Further Information

The wipe command should also look for hapis map save files and delete them when issuing a wipe or wipeall command. The file that needs to be edited to fix this is:
~/lgsm/functions/command_wipe.sh

## To Reproduce

1. start a hapsis island map by commenting out "worldsize=" adding this to start "parms=": +server.level HapisIsland 
2. start server
3. stop server 
4. wipe server with ~/rustserver wipe
5. issue command: ls -la ~/serverfiles/server/rustserver/ | grep hapis
6. note how hapis island .sav files are not gone

## Expected behaviour
1. start a hapsis island map by commenting out "worldsize=" adding this to start "parms=": +server.level HapisIsland 
2. start server
3. stop server 
4. wipe server with ~/rustserver wipe
5. issue command: ls -la ~/serverfiles/server/rustserver/ | grep hapis
6. no hapis island .sav files should be seen

**Comment by Frisasky** [comment]
it should be fixed in lgsm 12.1, update the lgsm script then try again

**Comment by StaticReality** [comment]
Linux GSM updated....
LinuxGSM - Rust - Version v20.1.1

wipe and wipeall commands still do not delete hapisisland.*.sav files as mentioned previously.
```
$ls -la ~/serverfiles/server/rustserver/ |grep hapis
-rw-rw-r-- 1 rustserver2 rustserver2 2089932 Mar 12 20:27 hapisisland.4096.109.190.sav
```

**Comment by Frisasky** [comment]
i have added hapis island wipe code, try replace the file "command_wipe.sh" in /lgsm/functions with this file and wipe again
https://raw.githubusercontent.com/Frisasky/LinuxGSM/wipe/lgsm/functions/command_wipe.sh

**Comment by StaticReality** [comment]
I downloaded the script and saved it to / overwrote `~/lgsm/functions/command_wipe.sh`
I tried out the new wipe script, still not working :(
`$ls -la ~/serverfiles/server/rustserver/|grep hapis
-rw-rw-r-- 1 rustserver2 rustserver2 2089932 Mar 12 20:27 hapisisland.4096.109.190.sav
 HapisIsland [rustserver2@gsm5 ~]$~/rustserver wipe

Rust Wipe
=================================
Information! No data to wipe was found

$~/rustserver wipeall

Rust Wipe
=================================
Information! No data to wipe was found
$ls -la ~/serverfiles/server/rustserver/|grep hapis
-rw-rw-r-- 1 rustserver2 rustserver2 2089932 Mar 12 20:27 hapisisland.4096.109.190.sav
$
`

The script (https://raw.githubusercontent.com/Frisasky/LinuxGSM/wipe/lgsm/functions/command_wipe.sh) looks like it should do the job, just appears to have a sntax error some where.

**Comment by h3o66** [comment]
Could you please check with the latest release ?
There where some changes recently.
