### ISSUE TITLE
Update get the wrong build from SteamCMD

### ISSUE THREAD

**Issue by HotoCocoaco** [GameServerManagers/LinuxGSM#2857]
Hosting TF2 server. It has a update yesterday, the build ID from SteamDB is 4972443
However when using ./tf2server update
it says:

[  OK  ] Update tf2server: Checking for update: SteamCMD

No update available
* Local build: 4952386
* Remote build: 4952386
https://steamdb.info/app/232250/

So I have to use force-update. is there any fix?

**Comment by PwnK** [comment]
This was fixed in 57243aae9a9ebf47c82979919646ea2da11ea9b2 so just run `./tf2server update-lgsm`

**Comment by dgibbs64** [comment]
We are getting a number of these issues still popping up. I need to review these issues as a priority

**Comment by LtKrunch** [comment]
I've been having the same problem with my ARK server, except force-update isn't finding a new version either. So I can't update my server, which means it's inaccessible atm.

**Comment by dgibbs64** [comment]
release https://github.com/GameServerManagers/LinuxGSM/releases/tag/v20.2.1 should have resolved this issue
