### ISSUE TITLE
Errors from ps for session leaders or group ID's

### ISSUE THREAD

**Issue by stevenboyd78** [GameServerManagers/LinuxGSM#2881]
## User Story

At seemingly random times, when I run `./arkserver details` it displays "error: list of session leaders OR effective group IDs was invalid"

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Ark: Survival Evolved]
* **Command:** [./arkserver details]
* **LinuxGSM version:** [v20.2.1]

## Further Information

```
arkserver@96gig:~$ ./arkserver details
error: list of session leaders OR effective group IDs was invalid

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
(standard_in) 1: syntax error
error: list of session leaders OR effective group IDs was invalid

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: list of session leaders OR effective group IDs was invalid

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).

Distro Details
===========================================================================================================================================================================================================================================================================
Distro:    Ubuntu 18.04.4 LTS
Arch:      x86_64
Kernel:    4.15.0-99-generic
Hostname:  96gig
Uptime:    0d, 2h, 32m
tmux:      tmux 2.6
glibc:     2.27

Server Resource
===========================================================================================================================================================================================================================================================================
CPU
Model:      Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz
Cores:      16
Frequency:  2261.216MHz
Avg Load:   2.32, 1.69, 1.22

Memory
Mem:       total  used  free   cached  available
Physical:  95GB   49GB  46GB   12GB    46GB
Swap:      2.0GB  0B    2.0GB

Storage
Filesystem:  /dev/sda1
Total:       458G
Used:        65G
Available:   370G

Network
Interface:    enp7s0f0
Link Speed:   1000Mb/s
IP:           ###.###.###.###
Internet IP:  ###.###.###.###

Game Server Resource Usage
===========================================================================================================================================================================================================================================================================
CPU Used:  %
Mem Used:  %  0MB

Storage
Total:        60G
Serverfiles:  22G
Backups:      20G

ARK: Survival Evolved Server Details
===========================================================================================================================================================================================================================================================================
Server name:        TheBoyd's Ark Server - TheIsland - (v310.68)
Server IP:          ###.###.###.###:7777
Internet IP:        ###.###.###.###:7777
Players:            0/10
Current map:        TheIsland
Default map:        TheIsland
Current game mode:  TestGameMode_Gaia_C
Master server:      false
Status:             ONLINE

arkserver Script Details
===========================================================================================================================================================================================================================================================================
Script name:            arkserver
LinuxGSM version:       v20.2.1
glibc required:         2.15
Discord alert:          on
Slack alert:            off
Email alert:            on
Pushbullet alert:       off
IFTTT alert:            off
Mailgun (email) alert:  off
Pushover alert:         off
Telegram alert:         off
Update on start:        off
User:                   arkserver
Location:               /home/arkserver
Config file:            /home/arkserver/serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

Backups
===========================================================================================================================================================================================================================================================================
No. of backups:  1
Latest backup:
    date:        Fri Apr 24 07:10:03 MDT 2020 (18 days ago)
    file:        /home/arkserver/lgsm/backup/arkserver-2020-04-24-124832.tar.gz
    size:        20G

Command-line Parameters
===========================================================================================================================================================================================================================================================================
./ShooterGameServer "TheIsland?SessionName=TheBoyd's Ark Server - TheIsland?AltSaveDirectoryName=TheIsland?listen?PreventSpawnAnimations=true?ShowFloatingDamageText=true?DisableWeatherFog=true?MultiHome=0.0.0.0?MaxPlayers=10?QueryPort=27015?RCONPort=27025?Port=7777?bRawSockets=7778 -NoTransferFromFiltering -clusterid=TheBoyd78 -server -log -automanagedmods -USEALLAVAILABLECORES -gameplaylogging -servergamelog -servergamelogincludetribelogs -ServerRCONOutputTribeLogs -usecache -webalarm "

Ports
===========================================================================================================================================================================================================================================================================
Change ports by editing the parameters in:
/home/arkserver/lgsm/config-lgsm/arkserver

Useful port diagnostic command:
netstat -atunp | grep ShooterGame

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game       INBOUND    7777   udp
> RAW        INBOUND    7778   udp
> Query      INBOUND    27015  udp
> RCON       INBOUND    27025  tcp

Status: ONLINE
```

## To Reproduce
Seems to happen randomly. I can run it one time and it's fine, and another time it dumps the ps help documentation.

## Expected behaviour
Not dump the ps help documentation.

**Comment by dgibbs64** [comment]
I believe this issue has been resolved in a more recent release. I will close this but please re-raise if still around

**Comment by underleo** [comment]
> I believe this issue has been resolved in a more recent release. I will close this but please re-raise if still around

Nope, the issue still existed.
when i run ./arkserver details/monitor, it will poped up about the command "ps" useage error.

**Comment by rainst** [comment]
I'm trying for the first time LinuxGSM and I'm getting this error every time I run the details or monitor scripts
I get the same error as the first report, do you think it's caused by how this distro is configured?

Server Info
- Distro: [Amazon Linux 2 (CentOS)]
- Game: [Valheim]
- Command: [./vhserver details -or- monitor]
- LinuxGSM version: [v21.1.3]

```
$ ./vhserver details
error: list of session leaders OR effective group IDs was invalid

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.
 (...)
```
