### ISSUE TITLE
Email feature seems to be broken on Slackware

### ISSUE THREAD

**Issue by Xylemon** [GameServerManagers/LinuxGSM#290]
So for the longest time the mail feature has been broken, and now I even get a bunch of nonsense when trying it out:

[ .... ] Email ts3-server: Sending notification to [email here]tail: cannot open '3' for reading: No such file or directory
[path to]/functions/fn_details_distro: line 32: [: : integer expression expected
tail: cannot open '3' for reading: No such file or directory
[path to]/functions/fn_details_distro: line 32: [: : integer expression expected
[  OK  ] Email ts3-server: Sending notification to [email here]

I do have Postfix and Mailutils installed.

**Comment by dgibbs64** [comment]
I definitely need access to an install of slackware so I can develop and test on slackware.

**Comment by dgibbs64** [comment]
Just tested on Ubuntu had not issues. can confirm Slackware issue.

**Comment by Xylemon** [comment]
Interesting, must be a dependency missing?

**Comment by dgibbs64** [comment]
Fixed the issue. Please delete the functions dir and test.
https://github.com/dgibbs64/linuxgameservers/commit/29d80e88ce8d8b44dbece05cb33c9ab64e9067fd

**Comment by Xylemon** [comment]
Did not fix, I'm still getting this error #218 and I don't know if that's causing the email not to be sent (although it says it's being sent which is odd).

**Comment by dgibbs64** [comment]
When I add code about tmux 1.8 the email error should!d disappear. I will also be using touch to make sure the log file is created even if the log is empty.

**Comment by Xylemon** [comment]
I'm not quite sure why email isn't getting sent, but sine updating Tmux #218 is fixed for me so that's one step closer to fixing this issue I hope.

**Comment by dgibbs64** [comment]
Is this now OK after the previous commit or are you still having issues?

**Comment by Xylemon** [comment]
It's still not working. I want to say it's related to dependencies here, not the script, but I'm not sure.

**Comment by dgibbs64** [comment]
Any update on this?

**Comment by Xylemon** [comment]
Haven't investigated it lately, will probably later today.

**Comment by dgibbs64** [comment]
email feature to be re-written in #566
