### ISSUE TITLE
Minecraft Bedrock (mcbserver) update appears to be broken

### ISSUE THREAD

**Issue by hysthub** [GameServerManagers/LinuxGSM#2980]
I cannot update mcbserver, tried on 2 servers same failure.

```
./mcbserver update
[ FAIL ] Updating mcbserver: Checking remote build: minecraft.net
```

**Comment by emerysteele** [comment]
hope this gets fixed soon

**Comment by dgibbs64** [comment]
I have raised an issue with Mojang https://bugs.mojang.com/browse/BDS-8068

**Comment by mspencerl87** [comment]
Update checked today..
Perhaps, Mojang has done something. I don't think its fixed, but they have done "Something" lol

No Updates Available
* Local build: 1.16.20.3
* Remote Build:

**Comment by mrmooo** [comment]
Hi there!

I ran an update yesterday and this worked for me. I received the same message above, it updated. However when I re-ran the update it told me the versions mismatched, even though they were the same (one had a .3 and the other .03). But I'm updated and working!

**Comment by mspencerl87** [comment]
@mrmooo Yea, similar story. My server will run but clients can't connect because it says "Server files out of date"
or something to that effect "Client/Server mismatch" can't remember.

**Comment by mspencerl87** [comment]
@dgibbs64 in the meantime while waiting for Mojang.
Could the update_minecraft_bedrock.sh config located in mcbserver/lgsm/functions
be changed in any meaningful way to work around the bug? as a temporary fix?
Thanks

**Comment by mrmooo** [comment]
Just want to clear up, I was on 10.16.10 and failing to check remote build, originally outlined. Failed for 3 weeks, until yesterday. I've been working in LGSM Discord channel trying to get another server situated. I ended up coming back to MC, ran the ./mcbserver update and it worked! Updated me from 1.16.10 to 1.16.20.3. When I re-run the ./mcbserver update it fails, saying version mismatch and attempts to download. Assuming it's due to the .03 vs .3 in the name.

**Comment by mspencerl87** [comment]
update 9/18/2020 

No update available
* Local build: 0
* Remote build:

Again

No update available
* Local build: 1.16.20.3
* Remote build:

Tried building a new MCB server fails to Download files.
mcbserver2@linuxgsm:~$ ./mcbserver start
[ FAIL ] Starting mcbserver: executable was not found
* /home/mcbserver2/serverfiles/bedrock_server

**Comment by mspencerl87** [comment]
Can you change the script to point to https://minecraft.azureedge.net/bin-linux/bedrock-server-1.16.40.02.zip

**Comment by h3o66** [comment]
The connected Pr should fix the inital update issue, but not the version problem

**Comment by mspencerl87** [comment]
@h3o66 
This did not fix the version as stated. But the serve has updated to 1.16.40.2 and is now running atleast.

**Comment by h3o66** [comment]
yeah - the issue on mojang site is still not solved

**Comment by sjwrick** [comment]
Looks like the issue is there again with version 1.17.1

**Comment by h3o66** [comment]
@sjwrick see #3505
