### ISSUE TITLE
[Bug]: ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded

### ISSUE THREAD

**Issue by Ren108** [GameServerManagers/LinuxGSM#4149]
### User story

Just want to start the server with bepinex installed by lgsm.

### Game

Valheim

### Linux distro

Ubuntu 22.04

### Command

command: start, command: mods-install

### Further information

Just switched from manual installed bepinex to lgsm installed bepinex (first removed all files from manual copy to serverfiles directory and then issued mi bepinexvh).
With manual install everthing was ok but now if i launch the server i get the message
ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

a couple of times in console and then the server is starting correctly. Its not showing up in logs.

### Relevant log output

```shell
Mono path[0] = '/home/vhserver/serverfiles/valheim_server_Data/Managed'
Mono config path = '/home/vhserver/serverfiles/valheim_server_Data/MonoBleedingEdge/etc'
Preloaded 'libsteam_api.so'
Unable to preload the following plugins:
	libparty.so
Initialize engine version: 2020.3.33f1 (915a7af8b0d5)
[Subsystems] Discovering subsystems at path /home/vhserver/serverfiles/valheim_server_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Completed reload, in  0.171 seconds
ERROR: Shader Sprites/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Sprites/Mask shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader GUI/Text Shader shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
UnloadTime: 1.505674 ms
03/25/2023 11:38:40: Starting to load scene:start
ERROR: Shader UI/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
Couldn't create a Convex Mesh from source mesh "default" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "default" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
ERROR: Shader Legacy Shaders/VertexLit shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard (Specular setup) shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
WARNING: Shader Unsupported: 'Autodesk Interactive' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Autodesk Interactive shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Autodesk Interactive' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Legacy Shaders/Particles/Additive shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Legacy Shaders/Particles/Alpha Blended shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Legacy Shaders/Particles/Alpha Blended Premultiply shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Unlit/Color shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Lux Lit Particles/ Bumped shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
Shader 'Lux Lit Particles/ Tess Bumped': fallback shader 'Lux Lit Particles/ Bumped Smoke' not found
WARNING: Shader Unsupported: 'Lux Lit Particles/ Tess Bumped' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Lux Lit Particles/ Tess Bumped shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Lux Lit Particles/ Tess Bumped' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader TextMeshPro/Mobile/Distance Field shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'TextMeshPro/Distance Field' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader TextMeshPro/Distance Field shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'TextMeshPro/Distance Field' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 13.282248 ms
Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
HDR Render Texture not supported, disabling HDR on reflection probe.
03/25/2023 11:38:45: Setting -savedir to: /home/vhserver/.config/unity3d/IronGate/Valheim
03/25/2023 11:38:45: Setting -logfile to: 
03/25/2023 11:38:45: Get create world Dedicated
03/25/2023 11:38:45: Using environment steamid 892970
03/25/2023 11:38:45: Using steam APPID:892970
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 15 milliseconds to initialize
Setting breakpad minidump AppID = 892970
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
03/25/2023 11:38:45: Server ID 90071992547409920
03/25/2023 11:38:45: Authentication:k_ESteamNetworkingAvailability_Waiting
03/25/2023 11:38:45: Steam game server initialized
03/25/2023 11:38:45: Using default prefs
03/25/2023 11:38:45: Valheim version:0.214.2
03/25/2023 11:38:45: Worldgenerator version setup:2
ERROR: Shader TextMeshPro/Sprite shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
03/25/2023 11:38:45: Render threading mode:SingleThreaded
03/25/2023 11:38:45: Missing audio clip in music respawn
03/25/2023 11:38:45: Builder started
03/25/2023 11:38:47: Loaded localization file #0 - 'localization' language: 'English'
03/25/2023 11:38:47: Loaded localization file #1 - 'localization_extra' language: 'English'
03/25/2023 11:38:47: Sending PlayFab login request (attempt 1)
03/25/2023 11:38:47: Login postponed until ID has been set.
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/libparty
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/libparty.so
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/party
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/libparty
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/libparty.so
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/libparty
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/libparty
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/libparty.so
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/party
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/libparty
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/libparty.so
Fallback handler could not load library /home/vhserver/serverfiles/valheim_server_Data/Mono/libparty
DllNotFoundException: party
  at (wrapper managed-to-native) PartyCSharpSDK.Interop.PFPInterop.PartyInitialize(byte[],PartyCSharpSDK.Interop.PARTY_HANDLE&)
  at PartyCSharpSDK.SDK.PartyInitialize (System.String titleId, PartyCSharpSDK.PARTY_HANDLE& handle) [0x00006] in <2a1ef85868414a97a033eac3f475139e>:0 
  at PlayFab.Party.PlayFabMultiplayerManager.InitializeImpl () [0x000be] in <2a1ef85868414a97a033eac3f475139e>:0 
  at PlayFab.Party.PlayFabMultiplayerManager._Initialize () [0x0000a] in <2a1ef85868414a97a033eac3f475139e>:0 
  at PlayFab.Party.PlayFabMultiplayerManager.Start () [0x00000] in <2a1ef85868414a97a033eac3f475139e>:0 

The shader Hidden/Dof/DepthOfFieldHdr (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) is not supported on this platform!
The image effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) has been disabled as it's not supported on the current platform.
The shader Hidden/SunShaftsComposite (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
The shader Hidden/SimpleClear (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
The image effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) has been disabled as it's not supported on the current platform.
03/25/2023 11:38:47: Game server connected
03/25/2023 11:38:47: Starting music menu
03/25/2023 11:38:47: UI Group status changed Menu = True

Unloading 17 unused Assets to reduce memory usage. Loaded Objects now: 137997.
Total: 188.591038 ms (FindLiveObjects: 19.637297 ms CreateObjectMapping: 27.701873 ms MarkObjects: 140.168145 ms  DeleteObjects: 1.082386 ms)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 25.300692 ms
HDR Render Texture not supported, disabling HDR on reflection probe.
HDR Render Texture not supported, disabling HDR on reflection probe.
03/25/2023 11:38:48: Using default prefs
03/25/2023 11:38:48: isModded: False
03/25/2023 11:38:48: Zonesystem Awake 799
03/25/2023 11:38:48: DungeonDB Awake 799
03/25/2023 11:38:48: Registering lobby
03/25/2023 11:38:48: Worldgenerator version setup:1
03/25/2023 11:38:52: Audioman already exist, destroying self

Unloading 100 unused Assets to reduce memory usage. Loaded Objects now: 142130.
Total: 248.436992 ms (FindLiveObjects: 21.424465 ms CreateObjectMapping: 32.486761 ms MarkObjects: 192.463444 ms  DeleteObjects: 2.060609 ms)

03/25/2023 11:39:05: Zonesystem Start 799
03/25/2023 11:39:06: Added 3 locations, 0 vegetations, 0 environments, 0 biome env-setups, 0 clutter  from locations_cp1
03/25/2023 11:39:06: Added 1 locations, 0 vegetations, 1 environments, 0 biome env-setups, 0 clutter  from locations_mountaincaves
03/25/2023 11:39:06: Added 27 locations, 25 vegetations, 5 environments, 1 biome env-setups, 3 clutter  from locations_mistlands
03/25/2023 11:39:06: DungeonDB Start 799
03/25/2023 11:39:07: ZRpc timeout set to 30s 
03/25/2023 11:39:07: Load world: Dedicated (Dedicated)
03/25/2023 11:39:07: Loading 727720 zdos , my id -178926771 data version:29
03/25/2023 11:39:14: Loaded 100000 dead zdos
03/25/2023 11:39:14: Removed 0 OLD generated ZDOS
03/25/2023 11:39:14: Loaded 9927 locations
03/25/2023 11:39:14: Unloading unused assets
Unloading 10 Unused Serialized files (Serialized files now loaded: 0)
The shader Hidden/Dof/DepthOfFieldHdr (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) is not supported on this platform!
The image effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) has been disabled as it's not supported on the current platform.
The shader Hidden/SunShaftsComposite (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
The shader Hidden/SimpleClear (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
The image effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) has been disabled as it's not supported on the current platform.
```

**Comment by Ren108** [comment]
tag game: Ark: Survival Evolved could be removed :D

**Comment by ghstwhl** [comment]
I am also experiencing this error, with a fresh install of LinuxGSM, Valheim, and the bepinexvh mod.

**Comment by ghstwhl** [comment]
I was able to clear this message by editing `./lgsm/functions/fix_vh.sh` and updating LD_LIBRARY_PATH to include the path to the instance's copy of doorstop_libs

**Comment by dgibbs64** [comment]
@ghstwhl could you paste your code changes please. I am currently looking at a fix

**Comment by ghstwhl** [comment]
I just forked the repo so I could submit a proper PR.  :)

**Comment by ghstwhl** [comment]
@dgibbs64 
Erk...  I started a PR, but there are a lot of steps in the process I don't have time to complete before my lunch is over.  Here's my corrected line 9 in lgsm/functions/fix_vh.sh

`export LD_LIBRARY_PATH="$(pwd)/serverfiles/BepInExPack_Valheim/doorstop_libs:$(pwd)/serverfiles/linux64:./linux64:${LD_LIBRARY_PATH}"`

This gets rid of the warning, but my server isn't starting at the moment so I can't confirm it's a complete fix.

**Comment by Zeekin** [comment]
+1 to this issue, experiencing the exact same thing.

The issue doesn't prevent the server from starting up, however it does mean mod injection is not happening; most mods being client side mean I can mostly get by without a fix, though it does break functionality of a few like epic-loot that would be good to get this working for.

I tried @ghstwhl fix however that just resulted in a different error:

> [ INFO ] Starting vhserver: BepInEx install detected, applying start exports
readlink: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
basename: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
rm: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
cat: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
readlink: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
basename: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
readlink: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
basename: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
wc: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
/home/vhserver/lgsm/functions/core_logs.sh: line 30: [: : integer expression expected
[ .... ] Starting vhserver: Ben and Ed suckssleep: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: 
dlopen
date: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
date: symbol lookup error: /home/vhserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym

Might have to look into manual install or something

**Comment by Makvagabo** [comment]
+1 I have the same result as @Zeekin

**Comment by Ilotoxy** [comment]
Hi, any update on this? Tried with a fresh install on Ubuntu 22.04. Installing the bepinexvh mod is just currently broken and does not work. I've tried modifying the fix_vh.sh import without success.

`[ INFO ] Starting vhserver: BepInEx install detected, applying start exports
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
/home/vhserver/lgsm/modules/core_logs.sh: line 30: [: Failed to hook dlsym, ignoring it. Error: no such function: dlsym
1: integer expression expected
[ .... ] Starting vhserver: ServerFailed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
./vhserver: line 475: to: command not found
./vhserver: line 476: -name 'Server' -password 12345 -port 2456 -world World -public 0 -savedir '/home/vhserver/.config/unity3d/IronGate/Valheim' -logFile '' -saveinterval 1800 -backups 4 -backupshort 7200 -backuplong 43200 : No such file or directory
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Found UnityPlayer, hooking into it instead
Found UnityPlayer, hooking into it instead
Found UnityPlayer, hooking into it instead
no server running on /tmp/tmux-1000/default
Found UnityPlayer, hooking into it instead`

**Comment by m33ts4k0z** [comment]
Hello.

This is still an issue. The mod doesn't work at all at the moment.

**Comment by dgibbs64** [comment]
Reading the docs it appears that the downloads should come from github now. I think this needs to bew reviewed

**Comment by natrius** [comment]
You mean reading https://docs.bepinex.dev/articles/user_guide/installation/index.html?tabs=tabid-nix and downloading the latest *nix from https://github.com/BepInEx/BepInEx/releases directly?

**Comment by ghstwhl** [comment]
> You mean reading https://docs.bepinex.dev/articles/user_guide/installation/index.html?tabs=tabid-nix and downloading the latest *nix from https://github.com/BepInEx/BepInEx/releases directly?
> 
> Installed it right now through linuxgsm and run into this error.

Unfortunately, Valheim doesn't work out of the box with the github BepInEx package.  You need it bundled with unstripped Unity DLLs.

https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/

**Comment by axe312ger** [comment]
Also have no luck getting it working on my debian VM. Adjusted the paths in LD_LIBRARY_PATH - it can find the lib now.. but goes crazy on on dlopen and dlsym:

<img width="431" alt="Screenshot 2023-10-24 at 12 25 58" src="https://github.com/GameServerManagers/LinuxGSM/assets/1737026/aa6b4e81-52b5-4970-b1f1-dc6e81290067">


Any ideas? :(

**Comment by GrubbyZebra** [comment]
> Also have no luck getting it working on my debian VM. Adjusted the paths in LD_LIBRARY_PATH - it can find the lib now.. but goes crazy on on dlopen and dlsym:
> 
> <img alt="Screenshot 2023-10-24 at 12 25 58" width="431" src="https://user-images.githubusercontent.com/1737026/277629320-aa6b4e81-52b5-4970-b1f1-dc6e81290067.png">
> Any ideas? :(
> 
> Edit:
> 
> Got it working manually on the very same (virtual) machine:
> 
> 1. More or less follow https://gist.github.com/mmercedes/64428eac49d970d6bcac99718a0066a3
> 2. Install https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/
> 3. Adjust configs
> 
> Server runs fine, could add my mods, could connect with my modded client.
> 
> Retried it in LGSM environment, but still running into these strange errors from above

Having the same issue, going to give this a try....

**Comment by smietanka** [comment]
Any update? Unfortunetly I have the same errors.. Can't play with mods because of this. I tried two different VPS machines and on both the same behavior :|

**Comment by gOOvER** [comment]
thats a problem with the libs

**Comment by almon17** [comment]
> Also have no luck getting it working on my debian VM. Adjusted the paths in LD_LIBRARY_PATH - it can find the lib now.. but goes crazy on on dlopen and dlsym:
> 
> <img alt="Screenshot 2023-10-24 at 12 25 58" width="431" src="https://user-images.githubusercontent.com/1737026/277629320-aa6b4e81-52b5-4970-b1f1-dc6e81290067.png">
> Any ideas? :(
> 
> Edit:
> 
> Got it working manually on the very same (virtual) machine:
> 
> 1. More or less follow https://gist.github.com/mmercedes/64428eac49d970d6bcac99718a0066a3
> 2. Install https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/
> 3. Adjust configs
> 
> Server runs fine, could add my mods, could connect with my modded client.
> 
> Retried it in LGSM environment, but still running into these strange errors from above

I tried this and still am having issues. I unzip the zip file and copy all the contents in BepInExPack_Valheim to /home/steam/Valheim. I edited the paths and start command to match the existing one and still received errrors. Could you post what your directory looks like a well we as your start_server_bepinex.sh script looks like?

**Comment by DSDV** [comment]
i have a fresh install where i encountered the same error.

but i used the `./vhserver mods-install` command to install valheim plus and assumed i needed bepinex as well? 
or is it enough to only install valheim plus since it comes with its own bepinex?

**Comment by gOOvER** [comment]
please read this:

```
As of Valheim 0.217.24, There is no longer a need for the unstripped corlibs to be shipped with BepInEx.
This version removes the corlibs and instructs doorstop not to include them.
For modders, this is important, as you'll want to make sure you are referencing Unity from the Game Folder now.
```

Startup must be rewritten ;)

**Comment by DSDV** [comment]
how does one do it? 
sorry i am no dev :/ 
is it ok to just install v+ when you have other mods which require bepinex?

**Comment by gOOvER** [comment]
> how does one do it? sorry i am no dev :/ is it ok to just install v+ when you have other mods which require bepinex?

v+ is dead. Search for the fork

**Comment by DSDV** [comment]
https://www.nexusmods.com/valheim/mods/2323 this one? 
Does it work with lgsm and do i need to install beinex seperatly to use it for xportal? 
is there a tutorial somewhere how to use it with lgsm? (sorry i am just a user not a dev ^^)

**Comment by DSDV** [comment]
apparently you have to: 
`If you are using [LGSM](https://linuxgsm.com/), go inside your instance config file and change executable to ./start_server_bepinex.sh to load the mod and your server arguments. More on LGSM config files can be found on [their homepage](https://docs.linuxgsm.com/configuration/linuxgsm-config).`

but the /lgsm/config-lgsm/vhserver/vhserver.cfg is empty and i have no clue how to put `./start_server_bepinex.sh` into there

**Comment by dgibbs64** [comment]
Can someone who has a bit of understanding on this give me some guidance on what we need to do to fix this. I have zero knowledge about VH mods so any help would be welcome.

**Comment by DSDV** [comment]
From what i understand https://github.com/Grantapher/ValheimPlus is the new fork. 
With the update from today that broke due to an old BepInEx version. 

But the game needs to be started with a modified startscript. 

i added this to the lgsm/config-lgsm/vhserver/vhserver.cfg
`executable="./start_server_bepinex.sh"`

that worked yesterday but the lgsm script gave an error that the server pw was not set even tho it was in the script. 
(also i did not yet figure out how to change server parameters like listing the server etc). 


Sadly today the game update broke sth: https://github.com/Grantapher/ValheimPlus/issues/36
i still trying to figure out if the workaround works on the server side

**Comment by chris3081** [comment]
I've been meaning to put a pull request in to fix this for the last week and I will try to in the next couple of days (just hadn't had time to test fully) . In the mean time this should fix the issue 

1. look in lgsm/modules for a file called mods-list.sh, if it doesn't exist  run ./vhserver mods-install which will copy it down, but ctrl+c out instead of installing valheim-plus

2. now find the file and edit it replacing the old repo "https://github.com/valheimPlus/ValheimPlus" with "https://github.com/Grantapher/ValheimPlus.git"

mod_info_valheimplus=(MOD "valheimplus" "Valheim PLUS" "${valeimpluslatestlink}" "ValheimPlus.tar.gz" "0" "LowercaseOff" "${systemdir}" "OVERWRITE" "ENGINES" "Valheim;" "NOTGAMES" "https://github.com/valheimPlus/ValheimPlus" "Mod to improve Valheim gameplay")

3. rerun vhserver mods-install and install the mod

I've got this far before work, I'l try find some time tonight to test it a bit better. I don't believe there are any other changes required.

**Comment by DSDV** [comment]
no rush (: 
sleep/health recovery is more important than a mod fix (: 

i got our server running the manual way again (: 
today's valheim update requires a bepinex update to the latest version (not currently shipped with V+). 
there alternativly ther is a  workaorund: https://github.com/Grantapher/ValheimPlus/issues/36#issuecomment-1798683440

maybe its a good idea to wait for V+ to release an updated version?

**Comment by chris3081** [comment]
Ahh thanks I will add that to the fix_vh.sh file

**Comment by chris3081** [comment]
Normally I would agree, but given its an open source project with no fixed deadlines, the new version isn't really set in stone. I'm thinking we can fix it today and when we understand what the new release looks like we will know if there are any issues then and we can raise a new issue if required.

**Comment by DSDV** [comment]
https://github.com/Grantapher/ValheimPlus/issues/36#issuecomment-1806933410
An update got released by Grantapher <3
Here is the release: https://github.com/Grantapher/ValheimPlus/releases

**Comment by Xruptor** [comment]
> I've been meaning to put a pull request in to fix this for the last week and I will try to in the next couple of days (just hadn't had time to test fully) . In the mean time this should fix the issue
> 
> 1. look in lgsm/modules for a file called mods-list.sh, if it doesn't exist  run ./vhserver mods-install which will copy it down, but ctrl+c out instead of installing valheim-plus
> 2. now find the file and edit it replacing the old repo "https://github.com/valheimPlus/ValheimPlus" with "https://github.com/Grantapher/ValheimPlus.git"
> 
> mod_info_valheimplus=(MOD "valheimplus" "Valheim PLUS" "${valeimpluslatestlink}" "ValheimPlus.tar.gz" "0" "LowercaseOff" "${systemdir}" "OVERWRITE" "ENGINES" "Valheim;" "NOTGAMES" "https://github.com/valheimPlus/ValheimPlus" "Mod to improve Valheim gameplay")
> 
> 3. rerun vhserver mods-install and install the mod
> 
> I've got this far before work, I'l try find some time tonight to test it a bit better. I don't believe there are any other changes required.

You need to update the following line as well, otherwise it will just pull the old repo:

`valeimpluslatestlink=$(curl --connect-timeout 10 -sL https://api.github.com/repos/valheimPlus/ValheimPlus/releases/latest | jq -r '.assets[]|select(.browser_download_url | contains("UnixServer.tar.gz")) | .browser_download_url')
#`

it should be

```
valeimpluslatestlink=$(curl --connect-timeout 10 -sL https://api.github.com/repos/Grantapher/ValheimPlus/releases/latest | jq -r '.assets[]|select(.browser_download_url | contains("UnixServer.tar.gz")) | .browser_download_url')
#
```

**Comment by gigafunk** [comment]
just fyi, val+ got all the attention here but the original issue this was opened for still exists.

this fix did not affect the mods-install of bepinexvh launching, it is still broken in the same way. bepinexvh is the base mod package install for valheim plus, and in affected in the same way, not launching and injecting mods because of this same error that might have just been fixed with val+

valheim plus is a mod pack which was supported first, and bepinexvh is the api framework mod that all mods are made within, and it looks like the the lgsm crew added support for a blank install of this(for custom mod mixes) when Val+ was unmaintained.

anyhow, thanks for everyone that works on this, i feel like an ass posting, but i feel like its an easy thing now while its fresh! its the same fix for val+ i think(minus the url change, bepinexvh installs just fine)

**Comment by DSDV** [comment]
V+ got the fix integrated later since the fix was an updated version of BepInEx ;) 
Or to say it the other way around the BepInEX update enabled a fixed version of V+ 

Also V+ (original) is deprecated and only a fork is updated since than (:

if you need a fix just copy paste & replace your server files with the latest bepinex version (:

**Comment by gigafunk** [comment]
The bepinex for v+ was fixed, but the non v+ bepinex install did not get the bepinex fix that the v+ install just got.  I am just calling attention to the fact there is another fix needed for the NON V+ bepinexvh installed with ./vhserver mods-install bepinexvh.

**Comment by chris3081** [comment]
No worries, I shall have a look into that over the next few days unless someone beats me to it.

**Comment by carlosgvaso** [comment]
Was this issue resolved? I can still see the error "ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded" when using the bepinexvh mod version. The server starts, but none of the mods for BepInEx are working.

**Comment by carlosgvaso** [comment]
> The bepinex for v+ was fixed, but the non v+ bepinex install did not get the bepinex fix that the v+ install just got. I am just calling attention to the fact there is another fix needed for the NON V+ bepinexvh installed with ./vhserver mods-install bepinexvh.
> 
> The version of bepinex installed with mods-install bepinexvh is current and works, its just the vhserver start does not start bepinex correctly, it fails in the way this original issue was opened for. When i move the files into the right places, i am able to start manually with the lgsm bepinexvh provided script (start_bepinex_server.sh or something).

@gigafunk , I'm running into the same issue. What files do I need to move to the right places. Could you explain what you did to get it running? Thanks in advance!

**Comment by DSDV** [comment]
V+ got updates
https://github.com/Grantapher/ValheimPlus/releases
maybe some update broke compatibility

**Comment by gigafunk** [comment]
apologies, but i forget, i was running without lgsm and moved to it, so I had a known good filesystem to copy the structure of. Now its on pause until the new land update.



i think what happens is the lgsm contributors update bepinex on the val+ version, and close the ticket and everyone thinks its done , until people with the custom mod version make new tickets and someone gets time to circle back and affect the change in the custom mod version. The amazing contributors dont know all the games they fix the lgsm for and they dont know bepinex needs to be  updated in two places for valheim, due to the val+ support and generic mod support options.

**Comment by joshschools** [comment]
Does anyone have the fix for this even if it is manual? @gigafunk

**Comment by VisMotrix** [comment]
Hi, quick update if some ppl have the same issue again (at least I did have problems) 

1. Update the 'libdoorstop_x64.so' 
1.1 Go to https://github.com/BepInEx/BepInEx - releases - downland newest  BepInEx_linux_x64_XXX.zip 
1.2 Replace /home/*gameuser*/gameserver/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so - with the downloaded libdoorstop.so (name it back to libdoorstop_x64.so!)

2 Fix the fix_vh.sh
2.1 Navigate to /home/*gameuser*/gameserver/lgsm/modules/fix_vh.sh 
2.2 replace line 9
 ```sh
export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
```
with
```sh
export LD_LIBRARY_PATH="$(pwd)/serverfiles/BepInExPack_Valheim/doorstop_libs:$(pwd)/serverfiles/linux64:./linux64:${LD_LIBRARY_PATH}"
export LD_PRELOAD="$(pwd)/serverfiles/BepInExPack_Valheim/doorstop_libs/libdoorstop_x64.so:${LD_PRELOAD}"
```
[opt Restart your server]
Hope this works for you

**Comment by fredtostaky** [comment]
[VisMotrix](https://github.com/VisMotrix) your fix resolve a previous error that give me a segmentation fault but and prevent the server to starting, but the first error "ERROR: ld.so: object [..]" still and my server loading without mods (but with BepInEx enable it seem).

**Comment by mikencyber** [comment]
Is there any fix for this in standalone BepInEx? Tried setting up a fresh LGSM Valheim server, initially installed bepinex via ./vhserver mods-install and got a bunch of "ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded"

Fixes shared by @VisMotrix unfortunately didn't work in my case, ended up doubling the errors received

**Comment by seriosbrad** [comment]
> Is there any fix for this in standalone BepInEx? Tried setting up a fresh LGSM Valheim server, initially installed bepinex via ./vhserver mods-install and got a bunch of "ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded"
> 
> Fixes shared by [@VisMotrix](https://github.com/VisMotrix) unfortunately didn't work in my case, ended up doubling the errors received

Did you make any progress fixing this? Same issues as you .

**Comment by Kovakin** [comment]
On attempting this fix for the Valheim client, modifying it somewhat to update the r2modman profiles with the manually updated BepInEx version, I continue to crash with no error reported in the console, but I do get these .blob files to generate https://gofile.io/d/hitVAO

**Comment by smietanka** [comment]
@seriosbrad @Kovakin @mikencyber 
This repo is dead.. guys..

https://www.nexusmods.com/valheim/mods/2323
There is a fork from grantapher, where everything works perfectly

**Comment by triuk** [comment]
LGSM mod handling is unreliable. A more effective method for setting up and maintaining a Valheim server with mods (as of September 2025) is available here: https://github.com/triuk/Valheim-Mod-Manager/tree/main
