### ISSUE TITLE
[Bug]: Ark Survival Evolved - Unable to specify new default map

### ISSUE THREAD

**Issue by dequeant** [GameServerManagers/LinuxGSM#4393]
### User story

I want to run an Ark Survival Evolved dedicate server running the default map: CrystalIsles

### Game

Ark Survival Evolved

### Linux distro

Debian 12

### Command

command: start

### Further information

WIthout changing anything whatsoever from the defaults after installation, when I run `./arkserver start` I get the following error (but the server still starts successfully on the default map):

```
/home/arkserver/lgsm/config-lgsm/arkserver/arkserver.cfg: line 41: unexpected EOF while looking for matching `"'
[ .... ] Starting arkserver: LinuxGSM./arkserver: eval: line 476: unexpected EOF while looking for matching `"'
```

Since the errors don't seem to affect anything, I'm fine with living with them, but I still need to change the map.  In "arkserver.cfg" I change the defaultmap to "CrystalIsles".  Then I again run "./arkserver start".  I again get the errors as before, but for some reason it still loaded "TheIsland" map despite me specifying CrystalIsles in the arkserver.cfg.

Suspecting it to be related to the errors I was getting, I investigate arkserver.cfg and identify a missing close quotes at the end of the serverparameters line.  
The original was: 
`startparameters="${defaultmap}?AltSaveDirectoryName=${altsavedirectoryname}?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?>`

I changed it to:
`startparameters="${defaultmap}?AltSaveDirectoryName=${altsavedirectoryname}?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?>"`

When I add the close quote, I no longer get the unexpected EOF errors, but it fails to start entirely and outputs this error:

```
[ .... ] Starting arkserver: LinuxGSMno server running on /tmp/tmux-1001/arkserver-82d55731
[ FAIL ] Starting arkserver: Unable to start LinuxGSM
```

I'm able to reproduce it consistently on a fresh install.  

### Steps to reproduce

Install LinuxGSM
Install arkserver
./arkserver start
You should get the errors, but it'll start in the map "TheIsland" regardless of what you specify in arkserver.cfg.  If you attempt to remedy the errors by adding a closequote to end of the startparameters line, you will no long get the original errors but the server will ultimately fail to start.

**Comment by dgibbs64** [comment]
The error shows you are missing a double quote `"` somewhere in your config. Clear this and your issue should be solved

**Comment by dequeant** [comment]
> The error shows you are missing a double quote `"` somewhere in your config. Clear this and your issue should be solved

It's the default config that installs with LinuxGSM.  I can delete it, in which case LinuxGSM will download its own copy of the file..... and I still get that error.  When I fix it, it fails to start.

**Comment by dgibbs64** [comment]
ensure that config-default is also deleted and ensure that linuxgsm is fully updated
