### ISSUE TITLE
[Bug]: Installing ut99server: jq is not installed when jq is installed, error on script line 158.

### ISSUE THREAD

**Issue by Archaicus** [GameServerManagers/LinuxGSM#4758]
### User story

When installing ut99 server on Ubuntu 24.04 LTS there is an error in the install script on line 158 calling for jq saying that it is not installed when it is.

### Game

Unreal Tournament 99

### Linux distro

Ubuntu 24.04

### Command

command: install

### Further information

The install script is throwing the error 

[ FAIL ] Installing ut99server: jq is not installed
/home/ut99server/lgsm/modules/update_ut99.sh: line 158: fn_script_log_fatal: command not found

jq is installed and even shows as a met dependency earlier in the install script.

Additional issue that I have worked around but is otherwise not documented on lgsm, needing to run "sudo dpkg --add-architecture i386" on 24.04 LTS so all the 32 bit dependencies are met to even attempt the install in the first place.

### Relevant log output

```shell
Feb 08 23:09:29.122 ut99server: INSTALL: INFO: Logs installed
Feb 08 23:09:29.452 ut99server: INSTALL: PASS: Downloading check_deps.sh...
Feb 08 23:09:30.125 ut99server: INSTALL: PASS: Checking ubuntu-24.04.csv
Feb 08 23:09:30.533 ut99server: INSTALL: PASS: Downloading ubuntu-24.04.csv...
Feb 08 23:09:34.384 ut99server: INSTALL: INFO: Required dependencies already installed.
Feb 08 23:09:34.675 ut99server: INSTALL: PASS: Downloading install_server_files.sh...
Feb 08 23:09:37.531 ut99server: INSTALL: PASS: Downloading ut99-server-469b-ultimate-linux.tar.xz...
Feb 08 23:09:37.932 ut99server: INSTALL: PASS: Verifying ut99-server-469b-ultimate-linux.tar.xz with MD5
Feb 08 23:09:37.933 ut99server: INSTALL: INFO: ut99-server-469b-ultimate-linux.tar.xz returned MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 08 23:09:37.935 ut99server: INSTALL: INFO: Expected MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 08 23:09:45.788 ut99server: INSTALL: PASS: Extracting ut99-server-469b-ultimate-linux.tar.xz
Feb 08 23:09:45.961 ut99server: INSTALL: PASS: clearing tmp directory /home/ut99server/lgsm/tmp
Feb 08 23:09:46.428 ut99server: INSTALL: PASS: Downloading update_ut99.sh...
Feb 08 23:09:47.026 ut99server: INSTALL: PASS: Downloading core_exit.sh...
Feb 08 23:09:47.085 ut99server: INSTALL: INFO: LinuxGSM version: v25.1.1
Feb 08 23:09:47.091 ut99server: INSTALL: PASS: core_exit.sh exiting with code: 0
Feb 08 23:10:49.546 ut99server: CORE: PASS: Downloading linuxgsm.sh...
Feb 08 23:10:53.152 ut99server: INSTALL: INFO: Logs installed
Feb 08 23:10:57.304 ut99server: INSTALL: INFO: Required dependencies already installed.
Feb 08 23:10:59.548 ut99server: INSTALL: PASS: Downloading ut99-server-469b-ultimate-linux.tar.xz...
Feb 08 23:10:59.950 ut99server: INSTALL: PASS: Verifying ut99-server-469b-ultimate-linux.tar.xz with MD5
Feb 08 23:10:59.951 ut99server: INSTALL: INFO: ut99-server-469b-ultimate-linux.tar.xz returned MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 08 23:10:59.953 ut99server: INSTALL: INFO: Expected MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 08 23:11:07.916 ut99server: INSTALL: PASS: Extracting ut99-server-469b-ultimate-linux.tar.xz
Feb 08 23:11:08.051 ut99server: INSTALL: PASS: clearing tmp directory /home/ut99server/lgsm/tmp
Feb 08 23:11:08.257 ut99server: INSTALL: INFO: LinuxGSM version: v25.1.1
Feb 08 23:11:08.267 ut99server: INSTALL: PASS: core_exit.sh exiting with code: 0
Feb 08 23:13:36.319 ut99server: CORE: PASS: Downloading linuxgsm.sh...
Feb 08 23:13:39.532 ut99server: INSTALL: INFO: Logs installed
Feb 08 23:13:43.695 ut99server: INSTALL: INFO: Required dependencies already installed.
Feb 08 23:13:46.456 ut99server: INSTALL: PASS: Downloading ut99-server-469b-ultimate-linux.tar.xz...
Feb 08 23:13:46.897 ut99server: INSTALL: PASS: Verifying ut99-server-469b-ultimate-linux.tar.xz with MD5
Feb 08 23:13:46.899 ut99server: INSTALL: INFO: ut99-server-469b-ultimate-linux.tar.xz returned MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 08 23:13:46.901 ut99server: INSTALL: INFO: Expected MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 08 23:13:54.870 ut99server: INSTALL: PASS: Extracting ut99-server-469b-ultimate-linux.tar.xz
Feb 08 23:13:55.040 ut99server: INSTALL: PASS: clearing tmp directory /home/ut99server/lgsm/tmp
Feb 08 23:13:55.246 ut99server: INSTALL: INFO: LinuxGSM version: v25.1.1
Feb 08 23:13:55.257 ut99server: INSTALL: PASS: core_exit.sh exiting with code: 0
Feb 08 23:22:56.651 ut99server: CORE: PASS: Downloading linuxgsm.sh...
Feb 08 23:22:59.978 ut99server: INSTALL: INFO: Logs installed
Feb 08 23:23:04.183 ut99server: INSTALL: INFO: Required dependencies already installed.
Feb 08 23:23:06.458 ut99server: INSTALL: PASS: Downloading ut99-server-469b-ultimate-linux.tar.xz...
Feb 08 23:23:06.902 ut99server: INSTALL: PASS: Verifying ut99-server-469b-ultimate-linux.tar.xz with MD5
Feb 08 23:23:06.915 ut99server: INSTALL: INFO: ut99-server-469b-ultimate-linux.tar.xz returned MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 08 23:23:06.927 ut99server: INSTALL: INFO: Expected MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 08 23:23:15.082 ut99server: INSTALL: PASS: Extracting ut99-server-469b-ultimate-linux.tar.xz
Feb 08 23:23:15.249 ut99server: INSTALL: PASS: clearing tmp directory /home/ut99server/lgsm/tmp
Feb 08 23:23:15.456 ut99server: INSTALL: INFO: LinuxGSM version: v25.1.1
Feb 08 23:23:15.462 ut99server: INSTALL: PASS: core_exit.sh exiting with code: 0
Feb 08 23:28:10.651 ut99server: CORE: PASS: Downloading linuxgsm.sh...
Feb 08 23:28:13.675 ut99server: INSTALL: INFO: Logs installed
Feb 08 23:28:17.908 ut99server: INSTALL: INFO: Required dependencies already installed.
Feb 08 23:28:20.443 ut99server: INSTALL: PASS: Downloading ut99-server-469b-ultimate-linux.tar.xz...
Feb 08 23:28:20.883 ut99server: INSTALL: PASS: Verifying ut99-server-469b-ultimate-linux.tar.xz with MD5
Feb 08 23:28:20.884 ut99server: INSTALL: INFO: ut99-server-469b-ultimate-linux.tar.xz returned MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 08 23:28:20.886 ut99server: INSTALL: INFO: Expected MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 08 23:28:28.763 ut99server: INSTALL: PASS: Extracting ut99-server-469b-ultimate-linux.tar.xz
Feb 08 23:28:28.936 ut99server: INSTALL: PASS: clearing tmp directory /home/ut99server/lgsm/tmp
Feb 08 23:28:29.141 ut99server: INSTALL: INFO: LinuxGSM version: v25.1.1
Feb 08 23:28:29.153 ut99server: INSTALL: PASS: core_exit.sh exiting with code: 0
```

### Steps to reproduce

Be running Ubuntu 24.04 LTS
Install needed 32bit apt support
create ut99server user
run install script
get error 
[ FAIL ] Installing ut99server: jq is not installed
/home/ut99server/lgsm/modules/update_ut99.sh: line 158: fn_script_log_fatal: command not found

NOTE: This machine is also running a Minecraft Java server from LGSM and it is working properly.  There is nothing else running on this machine.  It is supposed to be dedicated to game servers.

**Comment by dgibbs64** [comment]
Thanks for this. It was a bug. I have released a hotfix

**Comment by Archaicus** [comment]
I spooled up a new Ubuntu VM and can verify that the issues still exists.  The change is now it no longer reports that there is an error on line 158.  We now simply get [ FAIL ] Installing ut99server: jq is not installed.

From the log.

Feb 09 19:09:21.502 ut99server: INSTALL: INFO: Logs installed
Feb 09 19:09:24.491 ut99server: INSTALL: INFO: Required dependencies already installed.
Feb 09 19:09:27.069 ut99server: INSTALL: PASS: Downloading ut99-server-469b-ultimate-linux.tar.xz...
Feb 09 19:09:27.494 ut99server: INSTALL: PASS: Verifying ut99-server-469b-ultimate-linux.tar.xz with MD5
Feb 09 19:09:27.495 ut99server: INSTALL: INFO: ut99-server-469b-ultimate-linux.tar.xz returned MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 09 19:09:27.496 ut99server: INSTALL: INFO: Expected MD5 checksum: dba3f1122a5e60ee45ece7422fcf78f5
Feb 09 19:09:37.195 ut99server: INSTALL: PASS: Extracting ut99-server-469b-ultimate-linux.tar.xz
Feb 09 19:09:37.320 ut99server: INSTALL: PASS: clearing tmp directory /home/ut99server/lgsm/tmp
Feb 09 19:09:37.454 ut99server: INSTALL: FAIL: jq is not installed
Feb 09 19:09:37.460 ut99server: INSTALL: INFO: LinuxGSM version: v25.1.3
Feb 09 19:09:37.461 ut99server: INSTALL: FAIL: core_exit.sh exiting with code: 1

**Comment by Archaicus** [comment]
As of right now it everything seems to be working correctly.  Thanks for the updates.
