### ISSUE TITLE
[qlserver] Any chance we can have Quake Live added?

### ISSUE THREAD

**Issue by smt923** [GameServerManagers/LinuxGSM#507]
As of today, I believe, the server files can now be downloaded and Linux servers can be hosted (finally)

https://steamcommunity.com/sharedfiles/filedetails/?id=542966946

this nice guide has pretty much all the info, app id, some config info, etc, I should be able to test it too (unfortunately it's no longer free to play, if you ran it on steam while it was free you should have a copy though)

**Comment by dgibbs64** [comment]
I do have a copy. Cannot see why we cannot have a go at this.  However there is a backlog of server requests currently

**Comment by UltimateByte** [comment]
I could work on it once more important stuff is done.

**Comment by UltimateByte** [comment]
Done !

**Comment by dgibbs64** [comment]
Testing Quake Live. Still missing a complete details page. This will need to be completed.

**Comment by UltimateByte** [comment]
Sorry for closing, thought this https://github.com/dgibbs64/linuxgsm/pull/671 was enough.

**Comment by dgibbs64** [comment]
Closing now as happy this is complete
